sudo: required

services:
- docker

language: go

go:
- 1.10.x

go_import_path: github.com/prometheus/alertmanager

install:
#- git clone https://github.com/$TRAVIS_REPO_SLUG.git prometheus/alertmanager

script:
- VERSION=$(echo $TRAVIS_TAG | sed 's/^release-//' | sed 's/^v//')
- 'if [ -n "$TRAVIS_TAG" ]; then echo "$VERSION" > VERSION; fi'
# test front-end
- make clean
- cd ui/app/ && make && cd ../..
- make assets
#- git diff --exit-code
# test back-end
- make

before_deploy:
- make promu
- promu crossbuild
- promu crossbuild tarballs
- promu checksum .tarballs

deploy:
  provider: releases
  api_key:
    secure: pGc0MY871C4SnUfVn00juS1GlVnl3iT8jp6h0MeNAWm6CD37xma7rgohGwB0fibtlwoQ0TEeuco/K/ei3XdST2JgguMTXUzLKAy/0RwIG3ucVN/bjVoh3HFNwInqDDXDicpgxUx53YgEIhMT/hufvJLkg5YhbcDt2N2UEI25bNrIPdU9ZqQGsUEc86QoiccQMJSzt1YvSfHpB24El1YB0olMJw5I0PGBuG7r8PSbbPQU2flXTwuv646EVBYEOva6SfiONLFLrEbmueqHuodMStfrYVP4gVIdXN5p+pGX6k/EZwRG40ixjAiN8dCk6wN5ue4heuFHC+GOEoNLFA1HkYFilfyexWwyoR5jT8yLJJU4Zd3QNHBjlQm2rQcrNlVuFdK25S7tXtVOJZ809748jGl9nXrLaxf+cbfKFtAgOtvxNnuxSJy5XCBNL2NeYNPrvPcofJDmE9hQkCjw4TQ30qjNKIxOKFyBBUwEozxsOBWiTbqmTKwuCCBtA1fOVZOaBeUq6sQTCPLiuXFyfNIYV3x05EHft6sIT5dSTPZRRoG2GeFbgcomASQrXotYEBueJ3ltGDTTHTM6KNbSw9eLwXkgsiEPEcamWrp0JdLG49kkWRpPssrWwwlHQ1KV5AjDbHYxEQWd+wyW0gIcp25OrfkLU7XVyZRQFcLu81JFVJE=
  file_glob: true
  file: .tarballs/*
  skip_cleanup: true
  on:
    tags: true
    repo: criteo-forks/alertmanager
